Scripts/RemediationScripts/Remediate-AnonymousAccessOnContainers.ps1
Scripts/RemediationScripts/Remediate-ConfigASCTier.ps1
Scripts/RemediationScripts/Remediate-DontUseNonADIdentities.ps1
Scripts/RemediationScripts/Remediate-InvalidAADObjectRoleAssignments.ps1

…hZ_Dont_Use_NonAD_Identities"

 Adding support for classic role assignment in "Azure_Subscription_AuthZ_Dont_Use_NonAD_Identities"

---

Scripts/RemediationScripts/Remediate-ConfigAzureDefender.ps1

Update and rename Remediate-ConfigASCTier.ps1 to Remediate-ConfigAzureDefender.ps1

Update and rename Remediate-ConfigASCTier.ps1 to Remediate-ConfigAzureDefender.ps1

---

Scripts/RemediationScripts/Remediate-EnableHTTPSForAppServices.ps1

Required for use of Get-AzResource command

Add Az.Resources to pre-req modules list

---

Control coverage/Feature/SQLServer.md
Control coverage/Feature/Storage.md

Update the documentation for the following Controls:
* Azure_SQLDatabase_AuthZ_Use_AAD_Admin
* Azure_SQLDatabase_DP_Enable_TDE
* Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server
* Azure_SQLDatabase_NetSec_Dont_Allow_Universal_IP_Range
* Azure_SQLDatabase_Audit_Enable_Logging_and_Monitoring_Server
* Azure_SQLDatabase_AuthZ_Firewall_Deny_Access_AzureServices
* Azure_SQLDatabase_Audit_Enable_Vuln_Assessment
* Azure_SQLDatabase_SI_Remediate_Security_Vulnerabilities
* Azure_Storage_AuthN_Dont_Allow_Anonymous
* Azure_Storage_DP_Encrypt_In_Transit
* Azure_Storage_NetSec_Restrict_Network_Access
* Azure_Storage_DP_Use_Secure_TLS_Version

Update GitHub documentation for SQLServer (8), Storage (4) Controls

---

Control coverage/Feature/SQLServer.md

Add Synapse specific PowerShell commands for:
- Azure_SQLDatabase_DP_Enable_TDE
- Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server

Add Synapse specific PowerShell commands

---

Control coverage/Feature/NSG.md
Control coverage/Feature/NotificationHub.md
Control coverage/Feature/RedisCache.md
Control coverage/Feature/SQLManagedInstance.md
Control coverage/Feature/ServiceBus.md
Control coverage/Feature/ServiceFabric.md

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
</head>
<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr'>
ControlID
--
Azure_NotificationHub_AuthZ_Dont_Use_Manage_Access_Permission
Azure_NSG_NetSec_Dont_Open_Restricted_Ports
Azure_NSG_NetSec_Dont_Open_InBound_Any_Any
Azure_RedisCache_DP_Use_SSL_Port
Azure_ServiceBus_AuthZ_Dont_Use_Policies_At_SB_Namespace
Azure_ServiceFabric_AuthZ_Security_Mode_Enabled
Azure_ServiceFabric_AuthN_Client_AuthN_AAD_Only
Azure_ServiceFabric_DP_Set_Property_ClusterProtectionLevel
Azure_ServiceFabric_AuthN_NSG_Enabled
Azure_ServiceFabric_Audit_Publicly_Exposed_Load_Balancer_Ports …

Update doc for NotificationHub (1), NSG (2), RedisCache (1), ServiceBus (1), ServiceFabric (7), SQLManagedInstance (2)

---

Control coverage/Feature/SQLServer.md
Control coverage/Feature/VirtualMachineScaleSet.md

Updated the control specification of all the controls in Virtual machine scale set and tls control of SQL server.

Control Specification Updates (VMSS, SQLServer(TLS))

---

Control coverage/Feature/ContainerRegistry.md
Control coverage/Feature/VirtualNetwork.md

Remove '.' from DisplayName for Azure_ContainerRegistry_Config_Enable_Security_Scanning
Remove Italic formatting from DisplayName for Azure_ERvNet_NetSec_Dont_Add_UDRs_on_Subnets

Update Control Spec. - Fix DisplayNames

---

Control coverage/Feature/DBForMySql.md
Control coverage/Feature/DBForPostgreSQL.md
Control coverage/Feature/RedisCache.md

Added specs for NB-Controls:
1. Azure_DBforPostgreSQL_NetSec_Dont_Allow_Universal_IP_Range
2. Azure_DBforMySQL_AuthZ_Firewall_Deny_AzureServices_Access
3. Azure_RedisCache_BCDR_Use_RDB_Backup

Added specs for NB-Controls:

---

06-Customizing AzTS for your org/README.md

Replaced deadlinks with #. Also added a header message.

Replaced deadlinks with #

---

Control coverage/Feature/SubscriptionCore.md

Updated SubscriptionCore documentation with latest format

Updated SubscriptionCore documentation with latest format

---

Control coverage/Feature/LogicApps.md
Control coverage/README.md

Added LogicApps ControlSpec for newly added non-baseline controls.
Update ControlCoverage README.md with KeyVault and LogicApps options.

Added LogicApps ControlSpec; Updated ControlCoverage README

---

Control coverage/Feature/APIManagement.md
Control coverage/Feature/DBForPostgreSQL.md

Updated control spec for following two controls:
1. Azure_APIManagement_Audit_Enable_Diagnostics_Log
2. Azure_DBforPostgreSQL_Audit_Enable_Diagnostics_Log

Updated control specifications

---

Control coverage/Feature/SubscriptionCore.md

1. Azure_Subscription_Config_ASC_Defender - Update Control Settings to include "Containers" bundle.
2. Azure_Subscription_AuthZ_Remove_Management_Certs - Add deprecation notice.

Update Azure_Subscription_Config_ASC_Defender and Azure_Subscription_AuthZ_Remove_Management_Certs

---

Control coverage/Feature/CloudService.md
Control coverage/Feature/VirtualMachine.md
Control coverage/Feature/VirtualNetwork.md

Update recommendation/Control spec. verbiage, and others.

Control Spec. updates - ERvNet/Cloud Service/Virtual Machine Controls.

---

08-Secure by default/Secure Templates/ARM/APIManagement.json
08-Secure by default/Secure Templates/Bicep/APIManagement.bicep
08-Secure by default/Secure Templates/Bicep/APIManagement.parameters.json

Develop templates for the following Controls:
1. Azure_APIManagement_AuthN_Disable_Management_API
2. Azure_APIManagement_AuthN_Use_AAD_for_Client_AuthN
3. Azure_APIManagement_DP_Use_Secure_TLS_Version

Develop secure templates for API Management service

---

08-Secure by default/Secure Templates/ARM/RedisCache.json
08-Secure by default/Secure Templates/Bicep/RedisCache.bicep

Develop templates for the following Controls:
1. Azure_RedisCache_DP_Use_SSL_Port

Develop secure templates for Azure Redis Cache service

---

08-Secure by default/Secure Templates/ARM/APIManagement.json
08-Secure by default/Secure Templates/ARM/SQLDatabase.json
08-Secure by default/Secure Templates/ARM/SQLServer.json
08-Secure by default/Secure Templates/Bicep/APIManagement.bicep
08-Secure by default/Secure Templates/Bicep/APIManagement.parameters.json
08-Secure by default/Secure Templates/Bicep/RedisCache.bicep
08-Secure by default/Secure Templates/Bicep/SQLDatabase.bicep
08-Secure by default/Secure Templates/Bicep/SQLDatabase.parameters.json
08-Secure by default/Secure Templates/Bicep/SQLServer.bicep
08-Secure by default/Secure Templates/Bicep/SQLServer.parameters.json

Develop templates for the following Controls:
1. Azure_SQLDatabase_AuthZ_Use_AAD_Admin
2. Azure_SQLDatabase_DP_Enable_TDE
3. Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server

Develop secure templates for SQL Server service

---

08-Secure by default/Secure Templates/ARM/ServiceFabric.json
08-Secure by default/Secure Templates/Bicep/ServiceFabric.bicep
08-Secure by default/Secure Templates/Bicep/ServiceFabric.parameters.json

Develop secure templates for Service Fabric Controls.
Develop secure templates for the following Controls:
1. Azure_ServiceFabric_AuthN_Client_AuthN_AAD_Only
2. Azure_ServiceFabric_DP_Dont_Expose_Reverse_Proxy_Port
3. Azure_ServiceFabric_DP_Set_Property_ClusterProtectionLevel

Develop secure templates for Service Fabric Controls

---

Control coverage/Feature/VirtualMachine.md

Update Passed/Failed criteria to include JIT rules with Source as 'Any'.

Update Control Spec. - Azure_VirtualMachine_NetSec_Dont_Open_Restricted_Ports

---

Control coverage/Feature/APIManagement.md
Control coverage/Feature/AppService.md
Control coverage/Feature/ContainerRegistry.md
Control coverage/Feature/KubernetesService.md
Control coverage/Feature/RedisCache.md
Control coverage/Feature/ServiceFabric.md

Update Control Spec., Remediation Guidance
- Azure_RedisCache_DP_Use_SSL_Port
- Azure_APIManagement_DP_Use_Secure_TLS_Version
- Azure_APIManagement_AuthN_Disable_Management_API
- Azure_APIManagement_AuthN_Use_AAD_for_Client_AuthN
- Azure_KubernetesService_AuthN_Enabled_AAD
- Azure_KubernetesService_Deploy_Enable_Cluster_RBAC
- Azure_AppService_Config_Disable_Remote_Debugging
- Azure_ContainerRegistry_Config_Enable_Security_Scanning
- Azure_ServiceFabric_DP_Set_Property_ClusterProtectionLevel
- Azure_ServiceFabric_DP_Dont_Expose_Reverse_Proxy_Port

Update Control Spec., Remediation Guidance

---

Control coverage/Feature/VirtualMachine.md

Update Azure_VirtualMachine_NetSec_Dont_Open_Restricted_Ports - Add port 5986 to the scope of the evaluation.

Update Azure_VirtualMachine_NetSec_Dont_Open_Restricted_Ports - Add port 5986 to the scope of the evaluation.

---

Control coverage/Feature/APIManagement.md
Control coverage/Feature/RedisCache.md
Control coverage/Feature/ServiceFabric.md

Update Display Names - Azure_ServiceFabric_DP_Set_Property_ClusterProtectionLevel and Azure_ServiceFabric_DP_Dont_Expose_Reverse_Proxy_Port

Update Control Display Names

---

Scripts/RemediationScripts/AutoRemediation.ps1
Scripts/RemediationScripts/Remediate-AnonymousAccessOnContainers.ps1

Small Fix as Remediation Wrapper was breaking

Commented parameters

---

ReleaseNotes/RN220715.md

Hi Zia, 
Please help to review and approve.
Thanks

Users/v rijaiswal/az ts july external release

---

Scripts/RemediationScripts/AutoRemediation.ps1
Scripts/RemediationScripts/ControlRemediationSpecification.json
Scripts/RemediationScripts/ControlsEligibleForRemediationThroughUI.md
Scripts/RemediationScripts/Remediate-DisableRemoteDebuggingForAppServices.ps1
Scripts/RemediationScripts/Remediate-EnableAADForKubernetesService.ps1
Scripts/RemediationScripts/Remediate-EnableHTTPSForAppServices.ps1
Scripts/RemediationScripts/Remediate-SetAppServiceMinReqTLSVersion.ps1

Added changes to the three BRS scripts related to App Service.
The changes are:
1. Added code block to log the remediation details when running the BRS to support the ready-to-run remediation feature.
2. Added changes to change the look and feel of the script messages and make it more consistent.

Added changes to the App Service BRS to support Ready to run remediation script

---

ReleaseNotes/RN220929.md

AzTS Release Notes 220929

---

Control coverage/Feature/Storage.md

Updating Azure_Storage_AuthN_Dont_Allow_Anonymous control logic

Update Azure_Storage_AuthN_Dont_Allow_Anonymous control logic

---

Control coverage/Feature/HybridCompute.md
Control coverage/Feature/VirtualMachine.md
Control coverage/README.md

Added docs for Azure_HybridCompute_DP_Use_Secure_TLS_Version_Trial and Azure_VirtualMachine_DP_Use_Secure_TLS_Version_Trial
control

docs update for windows and arc windows server control

---

Scripts/RemediationScripts/Remediate-ConfigureWAFOnAzureFrontDoorCDN.ps1

Script File to Configure WAF on Azure Front Door CDN Profile

Remediation File Added for Azure Front Door Non Classic BRS

---

Control coverage/Feature/ApplicationGateway.md
Control coverage/README.md
Scripts/RemediationScripts/Readme.md
Scripts/RemediationScripts/Remediate-NSGConfigurationOnApplicationGatewaySubnet.ps1

Hey Team, 
please help to have a look and approve, thanks

Added the App Gateway NSG Configuration and Doc

---

Control coverage/Feature/CDN.md
Scripts/RemediationScripts/Readme.md
Scripts/RemediationScripts/Remediate-ConfigureWAFOnAzureFrontDoorCDN.ps1
Scripts/RemediationScripts/Remediate-EnableWAFPolicyStateOfAzFrontDoorCDN.ps1
Scripts/RemediationScripts/Remediate-SetWAFPolicyModeToPreventionForAzFrontDoorCDN.ps1

Azure Front Door CDN BRS and Documentation

Azure Front Door CDN BRS and Documentation 

---

Policies/APIManagement/Azure_APIManagement_AuthN_Disable_Management_API/Readme.md
Policies/APIManagement/Azure_APIManagement_AuthN_Disable_Management_API/Security - APIManagement - Audit API Management Service with Enabled Managament API.json
Policies/APIManagement/Azure_APIManagement_DP_Use_HTTPS_URL_Scheme/Readme.md
Policies/APIManagement/Azure_APIManagement_DP_Use_HTTPS_URL_Scheme/Security - APIManagement - Deny APIs with HTTP URL.json
Policies/KubernetesService/Azure_KubernetesService_AuthN_Enabled_AAD/Readme.md
Policies/Readme.md

added/updated the Custom Policy for KR51 Control

added/updated the Custom Policy for KR51 Control

---

Policies/ContainerRegistry/Azure_ContainerRegistry_Config_Enable_Security_Scanning/Readme.md
Policies/ContainerRegistry/Azure_ContainerRegistry_Config_Enable_Security_Scanning/Security - Container Registry - DeploySecurityScannerIdentity.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Readme.md
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - SQL Server - AuditSqlServerAuditingSettings.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - SQL Server - AuditSqlServerSecuritySettings.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - SQL Server - AuditSqlServerThreatDetection.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - SQL Server - Synapse SQL pools - DeploySqlServerAuditSettings.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - SQL Server - Synapse SQL pools - DeploySqlServerThreatDetection.json
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Security - Subscription - UpdateSecurityContacts.json

Policy Added for SQL Server

---

Policies/APIManagement/Azure_APIManagement_AuthN_Use_AAD_for_Client_AuthN/Readme.md
Policies/SQLServer/Azure_SQLDatabase_Audit_Enable_Threat_Detection_Server/Readme.md

Updated Policy Documentation for Multiple Policy Assessment.

Updated Policy Documentation for Multiple Policy Assessment.

---

Control coverage/Feature/ApplicationGateway.md

Added Helper script for Application gateway end to end encryption

Added Helper script for Application gateway end to end encryption 

---

Scripts/RemediationScripts/Readme.md

Updated readme

---

08-Secure by default/Secure Templates/ARM/Synapse.json
08-Secure by default/Secure Templates/Bicep/Synapse.bicep

ARM and Bicep template for Azure synapse workspace.
While creation of the synapse resource we will also create diagnostic settings for that particular synapse resource (Azure_SynapseWorkspace_Audit_Enable_DiagnosticSettings_Trial).

Added ARM And Bicep Template for Azure synapse

---

Control coverage/Feature/SubscriptionCore.md

Updated doc for Azure_Subscription_AuthZ_Dont_Grant_SPNs_Privileged_Roles, Azure_Subscription_AuthZ_Dont_Grant_SPNs_Privileged_Roles_RG

Doc update for SPN control at subscription and RG scope

---

11-Security Guidelines/README.md

Added security guidelines to set up conditional access policy for azure administrators

Added security guidelines to set up conditional access policy for azure administrators

---

Control coverage/Feature/DataShare.md

Updated documentation for  control Azure_DataShare_Audit_Enable_Diagnostic_Settings control to exclude all metric check

Updated documentation for  control Azure_DataShare_Audit_Enable_Diagnostic_Settings control to exclude all metric check

---

Scripts/RemediationScripts/Remediate-ConfigureManagedIdentityForMachineLearningWorkspace.ps1

This script will enable to Managed Identity for your compute resources in Machine Learning Workspaces.
Implemented for control Azure_MachineLearningWorkspace_AuthN_Use_Managed_Service_Identity.

Remediation | Enable Managed Identity for computes
